### ISSUE TITLE
(oauth.js:406) Error in OAuth Server: Failed to fetch identity from reddit. failed [403] {"error": 403}

### ISSUE THREAD

**Issue by bearcott** [PandaWhisperer/meteor-reddit-oauth#4]
stack trace:

> > Exception while invoking method 'login' Error: Failed to fetch identity from reddit. failed [403] {"error": 403}
> >   at getIdentity (packages/reddit-oauth/reddit_server.js:90:1)
> >   at Object.isJSON [as handleOauthRequest](packages/reddit-oauth/reddit_server.js:9:1)
> >   at OAuth._requestHandlers.(anonymous function) (packages/oauth2/packages/oauth2.js:16:1)
> >   at middleware (packages/oauth/packages/oauth.js:181:1)
> >   at packages/oauth/packages/oauth.js:154:1

**Comment by PandaWhisperer** [comment]
Merged PR and tagged new version. Thanks @bearcott.
